// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlc

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (website_id, name, link)
VALUES ($1, $2, $3)
RETURNING id, website_id, name, link, status, created_at, updated_at
`

type CreateCategoryParams struct {
	WebsiteID int32
	Name      string
	Link      string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.WebsiteID, arg.Name, arg.Link)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Name,
		&i.Link,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Name,
		&i.Link,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategoriesByStatus = `-- name: ListActiveCategoriesByStatus :many
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
WHERE status = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveCategoriesByStatusParams struct {
	Status EntityStatus
	Limit  int64
	Offset int64
}

func (q *Queries) ListActiveCategoriesByStatus(ctx context.Context, arg ListActiveCategoriesByStatusParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategoriesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Name,
			&i.Link,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCategoriesByWebsiteID = `-- name: ListActiveCategoriesByWebsiteID :many
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
WHERE website_id = $1 AND status = 'active'
ORDER BY created_at DESC    
LIMIT $2 OFFSET $3
`

type ListActiveCategoriesByWebsiteIDParams struct {
	WebsiteID int32
	Limit     int64
	Offset    int64
}

func (q *Queries) ListActiveCategoriesByWebsiteID(ctx context.Context, arg ListActiveCategoriesByWebsiteIDParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategoriesByWebsiteID, arg.WebsiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Name,
			&i.Link,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveCategories = `-- name: ListAllActiveCategories :many
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
WHERE status = 'active'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllActiveCategoriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllActiveCategories(ctx context.Context, arg ListAllActiveCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Name,
			&i.Link,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCategoriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllCategories(ctx context.Context, arg ListAllCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Name,
			&i.Link,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByStatus = `-- name: ListCategoriesByStatus :many
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCategoriesByStatusParams struct {
	Status EntityStatus
	Limit  int64
	Offset int64
}

func (q *Queries) ListCategoriesByStatus(ctx context.Context, arg ListCategoriesByStatusParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Name,
			&i.Link,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByWebsiteID = `-- name: ListCategoriesByWebsiteID :many
SELECT id, website_id, name, link, status, created_at, updated_at
FROM categories
WHERE website_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCategoriesByWebsiteIDParams struct {
	WebsiteID int32
	Limit     int64
	Offset    int64
}

func (q *Queries) ListCategoriesByWebsiteID(ctx context.Context, arg ListCategoriesByWebsiteIDParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByWebsiteID, arg.WebsiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Name,
			&i.Link,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET website_id = $2, name = $3, link = $4, status = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1   
RETURNING id, website_id, name, link, status, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID        int32
	WebsiteID int32
	Name      string
	Link      string
	Status    EntityStatus
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.WebsiteID,
		arg.Name,
		arg.Link,
		arg.Status,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Name,
		&i.Link,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
