// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createConfig = `-- name: CreateConfig :one
INSERT INTO configs (website_id, key, value)
VALUES ($1, $2, $3)
RETURNING id, website_id, key, value, created_at, updated_at
`

type CreateConfigParams struct {
	WebsiteID int32
	Key       string
	Value     json.RawMessage
}

type CreateConfigRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (CreateConfigRow, error) {
	row := q.db.QueryRowContext(ctx, createConfig, arg.WebsiteID, arg.Key, arg.Value)
	var i CreateConfigRow
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM configs
WHERE id = $1
`

func (q *Queries) DeleteConfig(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, id)
	return err
}

const getConfigByID = `-- name: GetConfigByID :one
SELECT id, website_id, key, value, created_at, updated_at
FROM configs
WHERE id = $1
`

type GetConfigByIDRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetConfigByID(ctx context.Context, id int32) (GetConfigByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getConfigByID, id)
	var i GetConfigByIDRow
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveConfigsByKey = `-- name: ListActiveConfigsByKey :many
SELECT id, website_id, key, value, created_at, updated_at
FROM configs
WHERE key = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveConfigsByKeyParams struct {
	Key    string
	Limit  int64
	Offset int64
}

type ListActiveConfigsByKeyRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListActiveConfigsByKey(ctx context.Context, arg ListActiveConfigsByKeyParams) ([]ListActiveConfigsByKeyRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveConfigsByKey, arg.Key, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveConfigsByKeyRow
	for rows.Next() {
		var i ListActiveConfigsByKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveConfigsByWebsiteID = `-- name: ListActiveConfigsByWebsiteID :many
SELECT id, website_id, key, value, created_at, updated_at
FROM configs
WHERE website_id = $1 AND status = 'active'
ORDER BY created_at DESC    
LIMIT $2 OFFSET $3
`

type ListActiveConfigsByWebsiteIDParams struct {
	WebsiteID int32
	Limit     int64
	Offset    int64
}

type ListActiveConfigsByWebsiteIDRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListActiveConfigsByWebsiteID(ctx context.Context, arg ListActiveConfigsByWebsiteIDParams) ([]ListActiveConfigsByWebsiteIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveConfigsByWebsiteID, arg.WebsiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveConfigsByWebsiteIDRow
	for rows.Next() {
		var i ListActiveConfigsByWebsiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllConfigs = `-- name: ListAllConfigs :many
SELECT id, website_id, key, value, created_at, updated_at
FROM configs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllConfigsParams struct {
	Limit  int64
	Offset int64
}

type ListAllConfigsRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListAllConfigs(ctx context.Context, arg ListAllConfigsParams) ([]ListAllConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllConfigsRow
	for rows.Next() {
		var i ListAllConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigsByStatus = `-- name: ListConfigsByStatus :many
SELECT id, website_id, key, value, created_at, updated_at
FROM configs
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConfigsByStatusParams struct {
	Status EntityStatus
	Limit  int64
	Offset int64
}

type ListConfigsByStatusRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListConfigsByStatus(ctx context.Context, arg ListConfigsByStatusParams) ([]ListConfigsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfigsByStatusRow
	for rows.Next() {
		var i ListConfigsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigsByWebsiteID = `-- name: ListConfigsByWebsiteID :many
SELECT id, website_id, key, value, created_at, updated_at
FROM configs
WHERE website_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConfigsByWebsiteIDParams struct {
	WebsiteID int32
	Limit     int64
	Offset    int64
}

type ListConfigsByWebsiteIDRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListConfigsByWebsiteID(ctx context.Context, arg ListConfigsByWebsiteIDParams) ([]ListConfigsByWebsiteIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigsByWebsiteID, arg.WebsiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfigsByWebsiteIDRow
	for rows.Next() {
		var i ListConfigsByWebsiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfig = `-- name: UpdateConfig :one
UPDATE configs
SET website_id = $2, key = $3, value = $4, status = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, website_id, key, value, created_at, updated_at
`

type UpdateConfigParams struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	Status    EntityStatus
}

type UpdateConfigRow struct {
	ID        int32
	WebsiteID int32
	Key       string
	Value     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (UpdateConfigRow, error) {
	row := q.db.QueryRowContext(ctx, updateConfig,
		arg.ID,
		arg.WebsiteID,
		arg.Key,
		arg.Value,
		arg.Status,
	)
	var i UpdateConfigRow
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
