// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: website.sql

package sqlc

import (
	"context"
)

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO websites (name, domain)
VALUES ($1, $2)
RETURNING id, name, domain
`

type CreateWebsiteParams struct {
	Name   string
	Domain string
}

type CreateWebsiteRow struct {
	ID     int32
	Name   string
	Domain string
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (CreateWebsiteRow, error) {
	row := q.db.QueryRowContext(ctx, createWebsite, arg.Name, arg.Domain)
	var i CreateWebsiteRow
	err := row.Scan(&i.ID, &i.Name, &i.Domain)
	return i, err
}

const deleteWebsite = `-- name: DeleteWebsite :exec
DELETE FROM websites
WHERE id = $1
`

func (q *Queries) DeleteWebsite(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteWebsite, id)
	return err
}

const getWebsiteByID = `-- name: GetWebsiteByID :one
SELECT id, name, domain, status, created_at, updated_at
FROM websites
WHERE id = $1
`

func (q *Queries) GetWebsiteByID(ctx context.Context, id int32) (Website, error) {
	row := q.db.QueryRowContext(ctx, getWebsiteByID, id)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWebsites = `-- name: ListAllWebsites :many
SELECT id, name, domain, status, created_at, updated_at
FROM websites
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllWebsitesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllWebsites(ctx context.Context, arg ListAllWebsitesParams) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listAllWebsites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Website
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebsites = `-- name: ListWebsites :many
SELECT id, name, domain, status, created_at, updated_at
FROM websites
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWebsitesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListWebsites(ctx context.Context, arg ListWebsitesParams) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listWebsites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Website
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebsitesByStatus = `-- name: ListWebsitesByStatus :many
SELECT id, name, domain, status, created_at, updated_at
FROM websites
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebsitesByStatusParams struct {
	Status EntityStatus
	Limit  int64
	Offset int64
}

func (q *Queries) ListWebsitesByStatus(ctx context.Context, arg ListWebsitesByStatusParams) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listWebsitesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Website
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebsite = `-- name: UpdateWebsite :one
UPDATE websites
SET name = $2, domain = $3, status = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, domain, status, created_at, updated_at
`

type UpdateWebsiteParams struct {
	ID     int32
	Name   string
	Domain string
	Status EntityStatus
}

func (q *Queries) UpdateWebsite(ctx context.Context, arg UpdateWebsiteParams) (Website, error) {
	row := q.db.QueryRowContext(ctx, updateWebsite,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Status,
	)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
